name: Main

on:
  push:
    branches: [main]

permissions:
  actions: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        platform: ['linux/amd64', 'linux/arm64']
        docker:
          - dockerfile: 'fpm/Dockerfile'
            namesuffix: ''
            key: 'fpm'
          - dockerfile: 'apache/Dockerfile'
            namesuffix: '/apache'
            key: 'apache'
        os: ['ubuntu-22.04']
    with:
      runner-os: ${{ matrix.os }}
      platform: ${{ matrix.platform }}
      cache-key: ${{ matrix.os }}-buildx-${{ matrix.platform }}-${{ matrix.docker.key }}-${{ github.ref_name }}-${{ github.sha }}
      cache-restore-keys: |
        ${{ matrix.os }}-buildx-${{ matrix.platform }}-${{ matrix.docker.key }}-${{ github.ref_name }}-
        ${{ matrix.os }}-buildx-${{ matrix.platform }}-${{ matrix.docker.key }}
      dockerfile: ${{ matrix.docker.dockerfile }}
      image-name-suffix: ${{ matrix.docker.namesuffix }}
