name: Pull Requests

on:
  pull_request:

permissions:
  actions: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-fpm:
    strategy:
      matrix:
        platform: ['linux/amd64', 'linux/arm64']
    name: Build FPM image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/build-images
        with:
          platform: ${{ matrix.platform }}
          cache-key: ${{ matrix.os }}-buildx-${{ matrix.platform }}-pr-${{ github.event.number }}-${{ github.sha }}
          cache-restore-keys: |
            ${{ matrix.os }}-buildx-${{ matrix.platform }}-pr-${{ github.event.number }}-
            ${{ matrix.os }}-buildx-${{ matrix.platform }}-pr-
            ${{ matrix.os }}-buildx-${{ matrix.platform }}-main-
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: 'fpm/Dockerfile'

  build-apache:
    strategy:
      matrix:
        platform: ['linux/amd64', 'linux/arm64']
    name: Build Apache image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/build-images
        with:
          platform: ${{ matrix.platform }}
          cache-key: ${{ matrix.os }}-buildx-${{ matrix.platform }}-pr-${{ github.event.number }}-${{ github.sha }}
          cache-restore-keys: |
            ${{ matrix.os }}-buildx-${{ matrix.platform }}-pr-${{ github.event.number }}-
            ${{ matrix.os }}-buildx-${{ matrix.platform }}-pr-
            ${{ matrix.os }}-buildx-${{ matrix.platform }}-main-
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: 'apache/Dockerfile'
          image-name-suffix: '/apache'
